version: '3.8'

services:
  backend:
    image: AutoSummarize-dotnet-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
