version: "3.8"

services:
  backend:
    env_file: .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - "${ASPNETCORE_HTTP_PORTS}:${ASPNETCORE_HTTP_PORTS}"

  frontend:
    env_file: .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_DOTNET_SERVICE_URL=${VITE_DOTNET_SERVICE_URL}
        - VITE_JAVA_SERVICE_URL=${VITE_JAVA_SERVICE_URL}
    ports:
      - "${FRONTEND_PORT}:80"

  java-backend:
    env_file: .env
    build:
      context: ./java-backend
      dockerfile: Dockerfile
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - "${JAVA_BACKEND_PORT}:8080"
