version: "3.8"

services:
  backend:
    image: judgementhc/autosummarize-backend:latest
    env_file: .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - "${ASPNETCORE_HTTP_PORTS}:${ASPNETCORE_HTTP_PORTS}"

  frontend:
    image: judgementhc/autosummarize-frontend:latest
    env_file: .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_DOTNET_SERVICE_URL=${VITE_DOTNET_SERVICE_URL}
    ports:
      - "${FRONTEND_PORT}:80"
