version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS}
        - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    env_file: .env
    ports:
      - "${ASPNETCORE_HTTP_PORTS}:${ASPNETCORE_HTTP_PORTS}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_DOTNET_SERVICE_URL=${VITE_DOTNET_SERVICE_URL}
        - VITE_JAVA_SERVICE_URL=${VITE_JAVA_SERVICE_URL}
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:80"

  # java-backend:
  #   build:
  #     context: ./java-backend
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   ports:
  #     - "${JAVA_BACKEND_PORT}:8080"
