dotnet:
  replicaCount: 1
  image:
    repository: judgementhc/autosummarize-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 5000
  resources:
    limits:
      memory: 128Mi
      cpu: 125m

java:
  replicaCount: 1
  image:
    repository: judgementhc/autosummarize-java-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 8080
  resources:
    limits:
      memory: 128Mi
      cpu: 125m

vue:
  replicaCount: 1
  image:
    repository: judgementhc/autosummarize-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 5555
  resources:
    limits:
      memory: 128Mi
      cpu: 125m
  env:
    - name: VITE_DOTNET_SERVICE_URL
      value: "http://my-app.local/api/dotnet"
    - name: VITE_JAVA_SERVICE_URL
      value: "http://my-app.local/api/java"

ingress:
  enabled: true
  host: my-app.local
  paths:
    dotnet:
      path: /api/dotnet
      serviceName: dotnet-service
      servicePort: 5000
    java:
      path: /api/java
      serviceName: java-service
      servicePort: 8080
    frontend:
      path: /
      serviceName: vue-service
      servicePort: 80
