{{- if .Values.dotnet }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
spec:
  replicas: {{ .Values.dotnet.replicaCount }}
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
        - name: dotnet-app
          image: "{{ .Values.dotnet.image.repository }}:{{ .Values.dotnet.image.tag }}"
          imagePullPolicy: {{ .Values.dotnet.image.pullPolicy }}
          resources:
            limits:
              memory: {{ .Values.dotnet.resources.limits.memory }}
              cpu: {{ .Values.dotnet.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.dotnet.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  selector:
    app: dotnet-app
  ports:
    - protocol: TCP
      port: {{ .Values.dotnet.service.port }}
      targetPort: {{ .Values.dotnet.service.port }}
{{- end }}

{{- if .Values.java }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: {{ .Values.java.replicaCount }}
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: "{{ .Values.java.image.repository }}:{{ .Values.java.image.tag }}"
          imagePullPolicy: {{ .Values.java.image.pullPolicy }}
          resources:
            limits:
              memory: {{ .Values.java.resources.limits.memory }}
              cpu: {{ .Values.java.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.java.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: {{ .Values.java.service.port }}
      targetPort: {{ .Values.java.service.port }}
  type: ClusterIP
{{- end }}

{{- if .Values.vue }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
spec:
  replicas: {{ .Values.vue.replicaCount }}
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
        - name: vue-app
          image: "{{ .Values.vue.image.repository }}:{{ .Values.vue.image.tag }}"
          imagePullPolicy: {{ .Values.vue.image.pullPolicy }}
          resources:
            limits:
              memory: {{ .Values.vue.resources.limits.memory }}
              cpu: {{ .Values.vue.resources.limits.cpu }}
          ports:
            - containerPort: 80
          env:
            {{- range .Values.vue.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: vue-service
spec:
  selector:
    app: vue-app
  ports:
    - protocol: TCP
      port: {{ .Values.vue.service.port }}
      targetPort: 80
{{- end }}