{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.paths.dotnet.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.paths.dotnet.serviceName }}
                port:
                  number: {{ .Values.ingress.paths.dotnet.servicePort }}
          - path: {{ .Values.ingress.paths.frontend.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.paths.frontend.serviceName }}
                port:
                  number: {{ .Values.ingress.paths.frontend.servicePort }}
{{- end }}
